name: Deploy Service to Azure AKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/token-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/token-service:latest

      - name: Set up Azure CLI
        uses: azure/cli@v2

      - name: AKS login
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Update Deployment in AKS
        run: |
          kubectl set image deployment/token-service-deployment token-service=${{ secrets.DOCKERHUB_USERNAME }}/token-service:latest
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/token-service-deployment
          kubectl get services token-service